#!/usr/bin/env python3


import json
import locale
import sys
import collections
import mimetypes
import os.path


# Custom modules provided by Qwiklabs
import reports
import emails

# Import for the optional visual pie chart challenge
from reportlab.graphics.shapes import Drawing
from reportlab.graphics,charts.piecharts import Pie
from reportlab.graphics.charts.legends import Legend

def load_data(filename):
  """Loads the contents of filename as a JSON file."""
  with open(filename) as json_file:
    data = json.load(json_file)
  return data


def format_car(car):
  """Given a car dictionary, returns a nicely formatted name."""
  return "{} {} ({})".format(car["car_make"], car["car_model"], car["car_year"])


def process_data(data):
  """Analyzes the data, looking for maximums.

  Returns a list of lines that summarize the information.
  """
  max_revenue = {"revenue": 0}
  # Added max_sales and car_year_sales to calculate the car model that has the most sales and the most popular car_year across all car
  max_sales = {"total_sales": 0}
  car_year_sales = collections.defaultdict(int)

  for item in data:
    # Calculate the revenue generated by this model (price * total_sales)
    # We need to convert the price from "$1234.56" to 1234.56
    item_price = locale.atof(item["price"].strip("$"))
    item_revenue = item["total_sales"] * item_price
    
    # 1. Track the car model with the most revenue
    if item_revenue > max_revenue["revenue"]:
      item["revenue"] = item_revenue
      max_revenue = item

    # TODO: also handle max sales
    # TODO: also handle most popular car_year

    # 2. Track the car model which had the most sales
    if item["total_sales"] > max_sales["total_sales"]:
      max_sales = item

    # 3. Add the total sales per car year to find the overall popular year
    car_year_sales[item["car"]["car_year"]] += item["total_sales"]

  # Locate the most popular year based on total sales accumulated
  most_popular_year = max(car_year_sales, key=car_year_sales.get)
  most_popular_sales = car_year_sales[most_popular_year]
    
  summary = [
    "The {} generated the most revenue: ${}".format(format_car(max_revenue["car"]), max_revenue["revenue"]),
    "The {} had most sales: {}".format(format_car(max_sales["car"]), max_sales["total_sales"]);
    "The most popular year was {} with {} sales.".format(most_popular_year, most_popular_sales) 
  ]

  return summary


def cars_dict_to_table(car_data):
  """Turns the data in car_data into a list of lists."""
  table_data = [["ID", "Car", "Price", "Total Sales"]]

  # CHALENGE 1: Sort the list of cars in the PDF by total sales descending
  sorted_car_data = sorted(car_data, key=lambda k: k['total_sales'], reverse=True)

  for item in car_data:
    table_data.append([item["id"], format_car(item["car"]), item["price"], item["total_sales"]])
  return table_data

def generate_sales_pie_chart(car_data):
  """CHALLENGE 2: Create a pie chart for the total sales of each car made."""

  # Add sales data together by make
  make_sales = collections.defaultdict(int)
  for item in car_data:
    make_sales[item["car"]["car_make"]] += item["total_sales"]

  # Sort data Layout for clean colour slice matching
  sorted_makes = sorted(make_sales.items(), key=lambda x: x[1], reverse=True)
  labels = [make for make, sales in sorted_makes]
  data = [sales for make, sales in sorted_makes]

  # Initialize drawing container
  d =  Drawing(400, 200)

  Configure Pie layout
    = Pie()
    .x = 20
    .y = 20
    .width = 160
    .height = 160
    .data = data
    .labels = [str(sales) for sales in data]
    .sideLabels = True
    add(pc)

  Configure Chart Legend layout
  gend = Legend()
  gend.x = 240
  gend.y = 180
  gend.dx = 8
  gend.dy = 8
  gend.fontName = 'Helvita'
  gend.fontSize = 9
  gend.boxAnchor = 'nw'
  gend.columnMaximum = 'right'
  gend.colorNamePairs = [(pc.slices[i].fillColor, labels[i]) for i in range(len(data))]
  add(legend)

  turn d

    

def main(argv):
  """Process the JSON data and generate a full report out of it."""
  data = load_data("car_sales.json")
  summary = process_data(data)
  print(summary)
  # TODO: turn this into a PDF report

  # TODO: send the PDF report as an email attachment


if __name__ == "__main__":
  main(sys.argv)
