#!/usr/bin/env python3


import json
import locale
import sys
import collections
import mimetypes
import os.path


# Custom modules provided by Qwiklabs
import reports
import emails

# Import for the optional visual pie chart challenge
from reportlab.graphics.shapes import Drawing
from reportlab.graphics,charts.piecharts import Pie
from reportlab.graphics.charts.legends import Legend

def load_data(filename):
  """Loads the contents of filename as a JSON file."""
  with open(filename) as json_file:
    data = json.load(json_file)
  return data


def format_car(car):
  """Given a car dictionary, returns a nicely formatted name."""
  return "{} {} ({})".format(car["car_make"], car["car_model"], car["car_year"])


def process_data(data):
  """Analyzes the data, looking for maximums.

  Returns a list of lines that summarize the information.
  """
  max_revenue = {"revenue": 0}
  # Added max_sales and car_year_sales to calculate the car model that has the most sales and the most popular car_year across all car
  max_sales = {"total_sales": 0}
  car_year_sales = collections.defaultdict(int)

  for item in data:
    # Calculate the revenue generated by this model (price * total_sales)
    # We need to convert the price from "$1234.56" to 1234.56
    item_price = locale.atof(item["price"].strip("$"))
    item_revenue = item["total_sales"] * item_price
    
    # 1. Track the car model with the most revenue
    if item_revenue > max_revenue["revenue"]:
      item["revenue"] = item_revenue
      max_revenue = item

    # TODO: also handle max sales
    # TODO: also handle most popular car_year

    # 2. Track the car model which had the most sales
    if item["total_sales"] > max_sales["total_sales"]:
      max_sales = item

    # 3. Add the total sales per car year to find the overall popular year
    car_year_sales[item["car"]["car_year"]] += item["total_sales"]

  # Locate the most popular year based on total sales accumulated
  most_popular_year = max(car_year_sales, key=car_year_sales.get)
  most_popular_sales = car_year_sales[most_popular_year]
    
  summary = [
    "The {} generated the most revenue: ${}".format(format_car(max_revenue["car"]), max_revenue["revenue"]),
    "The {} had most sales: {}".format(format_car(max_sales["car"]), max_sales["total_sales"]);
    "The most popular year was {} with {} sales.".format(most_popular_year, most_popular_sales) 
  ]

  return summary


def cars_dict_to_table(car_data):
  """Turns the data in car_data into a list of lists."""
  table_data = [["ID", "Car", "Price", "Total Sales"]]

  # CHALENGE 1: Sort the list of cars in the PDF by total sales descending
  sorted_car_data = sorted(car_data, key=lambda k: k['total_sales'], reverse=True)

  for item in car_data:
    table_data.append([item["id"], format_car(item["car"]), item["price"], item["total_sales"]])
  return table_data

def generate_sales_pie_chart(car_data):
  """CHALLENGE 2: Create a pie chart for the total sales of each car made."""

  # Add sales data together by make
  make_sales = collections.defaultdict(int)
  for item in car_data:
    make_sales[item["car"]["car_make"]] += item["total_sales"]

  # Sort data Layout for clean colour slice matching
  sorted_makes = sorted(make_sales.items(), key=lambda x: x[1], reverse=True)
  labels = [make for make, sales in sorted_makes]
  data = [sales for make, sales in sorted_makes]

  # Initialize drawing container
  d =  Drawing(400, 200)

  # Configure Pie layout
  pc = Pie()
  pc.x = 20
  pc.y = 20
  pc.width = 160
  pc.height = 160
  pc.data = data
  pc.labels = [str(sales) for sales in data]
  pc.sideLabels = True
  d.add(pc)

  # Configure Chart Legend layout
  legend = Legend()
  legend.x = 240
  legend.y = 180
  legend.dx = 8
  legend.dy = 8
  legend.fontName = 'Helvita'
  legend.fontSize = 9
  legend.boxAnchor = 'nw'
  legend.columnMaximum = 'right'
  legend.colorNamePairs = [(pc.slices[i].fillColor, labels[i]) for i in range(len(data))]
  d.add(legend)

  return d

def main(argv):
  """Process the JSON data and generate a full report out of it."""
  data = load_data("car_sales.json")
  summary = process_data(data)
  print(summary)

  # TODO: turn this into a PDF report
  # 1. Format text strings with HTML breaks '<br/>'
  paragraph = "<br/>".join(summary)

  # Process structured matrix for table
  table_data = cars_dict_to_table(date)

  # Process pie chart asset
  chart = generate_sales_pie_chart(data)

  # TODO: send the PDF report as an email attachment
  title = "Sales summary for last month"
  attachment = "/tmp/cars.pdf"

  # Calling reporting module to write PDF out to disk destination
  reports.generate(attachment, title, paragraph, table_data, chart)

  # Email Configuration
  sender = "automation@example.com"
  receiver = "student@example.com"

  # Format text strings with line break '\n'
  body = "\n".join(summary)

  # Generate email payload using target parameters and send the scripts
  message = emails.generate(sender, receiver, title, body, attachment)
  emails.send(message)

if __name__ == "__main__":
  main(sys.argv)
